# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='galleria.Category')),
                ('location', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='galleria.Location')),
            ],
        ),
    ]
