# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria', '0005_auto_20180503_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Illustrations', 'Illustrations'), ('Interior', 'Interior'), ('Random', 'Random'), ('Siberian', 'Siberian'), ('Wakanda', 'Wakanda')], max_length=15),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('Poka Universe', 'Poka Universe'), ('Singapore', 'Singapore'), ('Nairobi, Kenya', 'Nairobi, Kenya'), ('Siberia', 'Siberia'), ('Wakanda', 'Wakanda')], max_length=20),
        ),
    ]
